package top.alazeprt.sfmod.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class AndyLauAnimations {
        public static final Animation WALK = Animation.Builder.create(2f).looping()
                .addBoneAnimation("leg1",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 2.6f, 5.7f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 2.6f, -5.7f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("leg1",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("leg2",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 2.6f, -5.7f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 2.6f, 5.7f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("leg2",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("hand1",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 2.3f, -12.15f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 2.3f, 12.15f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("hand1",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("hand2",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 1.5f, 9.2f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 1.5f, -9.2f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("hand2",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(0.5f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1.5f, AnimationHelper.createRotationalVector(-30f, 2.3f, -12.15f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC))).build();
        public static final Animation IDLE = Animation.Builder.create(2f).looping()
                .addBoneAnimation("hand2",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(0.9f, -0.2f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("hand2",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("hand1",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(-1f, -0.1f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("hand1",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC))).build();
}
